2

diff --git a/.github/workflows/approver.yaml b/.github/workflows/approver.yaml
--- a/.github/workflows/approver.yaml
+++ b/.github/workflows/approver.yaml
@@ -27,18 +27,33 @@ jobs:
       - name: Job 3
         run: echo "This is job 3"
 
-  approval:
-    runs-on: ubuntu-latest
-    environment: Sample
+approval:
+    if: github.event_name == 'workflow_dispatch'
     needs: job3
-    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
+    runs-on: ubuntu-latest
     steps:
-      - name: Trigger Status Check
+      - name: Check for keyword
         run: |
-          echo "Pending approval..."
-          # Perform necessary steps, such as waiting for an approval
+          keyword=${{ github.event.inputs.keyword }}
+          if [[ $keyword == "releaseit" ]]; then
+            echo "Keyword matched. Proceeding..."
+          else
+            echo "Keyword not matched. Aborting..."
+            exit 1
+          fi
 
-      - name: Perform action after approval
+      - name: Get Review Comments
+        id: comments
+        uses: octokit/request-action@v2.x
+        with:
+          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews
+          headers: |
+            Authorization: Bearer ${{ secrets.PAT }} # Replace with your Personal Access Token (PAT)
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Print Review Comments
         run: |
-          # Perform actions after the approval check
-          echo "Approval obtained, performing actions..."
+          comments="${{ steps.comments.outputs.data }}"
+          echo "Reviewer Comments:"
+          echo "$comments"
